name: test

on:
  pull_request:
  push:
    branches: [master]

jobs:
  mix:
    runs-on: ubuntu-latest

    env:
      MIX_ENV: test

    strategy:
      matrix:
        elixir: ["1.13", "1.14"]
        otp: ["24", "25", "26"]

    steps:
      - uses: actions/checkout@v3

      - uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - uses: actions/cache@v3
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ matrix.otp }}-${{ matrix.elixir }}-${{ github.head_ref || github.ref }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{ matrix.otp }}-${{ matrix.elixir }}-${{ github.head_ref || github.ref }}-
            ${{ runner.os }}-mix-${{ matrix.otp }}-${{ matrix.elixir }}-refs/heads/master-
            ${{ runner.os }}-mix-${{ matrix.otp }}-${{ matrix.elixir }}-master-
            ${{ runner.os }}-mix-${{ matrix.otp }}-${{ matrix.elixir }}-

      - run: mix deps.get --only test
      - run: mix compile --warnings-as-errors
      - run: mix format --check-formatted
      - run: mix test
